"""initial schema

Revision ID: 56b702ce2307
Revises: 
Create Date: 2026-06-17 09:33:56.355976

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '56b702ce2307'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Ensure the enum type exists before creating tables that reference it.
    visibility_enum = sa.Enum('public_edit', 'public_view', 'private', name='visibility')
    visibility_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_subject', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('pads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('visibility', sa.Enum('public_edit', 'public_view', 'private', name='visibility'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('crdt_snapshot', sa.LargeBinary(), nullable=True),
    sa.Column('crdt_snapshot_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pads_last_opened_at'), 'pads', ['last_opened_at'], unique=False)
    op.create_index(op.f('ix_pads_owner_id'), 'pads', ['owner_id'], unique=False)
    op.create_index(op.f('ix_pads_slug'), 'pads', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pads_slug'), table_name='pads')
    op.drop_index(op.f('ix_pads_owner_id'), table_name='pads')
    op.drop_index(op.f('ix_pads_last_opened_at'), table_name='pads')
    op.drop_table('pads')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # Drop the enum type if present (idempotent).
    visibility_enum = sa.Enum('public_edit', 'public_view', 'private', name='visibility')
    visibility_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
